version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "11:45"
    open-pull-requests-limit: 5
    labels:
      - "nuget dependencies"
