version: 2
updates:
  - package-ecosystem: "nuget" 
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "02:53"
    open-pull-requests-limit: 20
    labels:
      - "nuget dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
 
