version: 2
updates:
  - package-ecosystem: "nuget" 
    directory: "/"
    target-branch: "develop-dependabot"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 4
    labels:
      - "nuget dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
 
