---
name: CI/CD with Dependabot
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version:
          - 6.0.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore
        run: dotnet restore "Mango.Web"
      - name: Build
        run: dotnet build "Mango.Web" --configuration Release --no-restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Bump versions
        uses: SiqiLu/dotnet-bump-version@2.1.0
        with:
            version_files: "**/*.csproj"
            version_mask: 0.0.1
            version_overwrite: "*.*.*.*"
            github_token: ${{ secrets.GITHUB_TOKEN }}
  dependabot:
    name: Dependabot fetch metadata
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-commit-verification: false
