---
name: CI/CD with Dependabot
on:
  push:
    branches:
      #- 'main'
      - 'feature/**'
      - 'dependabot/**'
jobs:
  dependabot:
    name: Dependabot fetch metadata
    runs-on: ubuntu-latest
    #if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-commit-verification: false
  upgrade_version:
    name: Upgrade NET Version
    runs-on: windows-latest
    #if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Bump versions
        uses: SiqiLu/dotnet-bump-version@2.0.0
        with:
          version_files: "**/*.csproj"
          version_mask: 0.0.1.0
          version_overwrite: "*.*.*.*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
  format-code:
    needs: upgrade_version
    name: Create commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Bump versions
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Updated API Version
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
  
