---
name: CI/CD with Dependabot
on:
  push:
    branches:
      #- 'dependabot/**'  
      #- 'feature/**'  
      - 'main'  
  pull_request:
   branches:
    - main
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  types:
  #    - opened
  #    - synchronize tes
jobs:
  # build:
  #   name: Build application
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       dotnet-version:
  #         - 6.0.x
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Setup .NET Core
  #       uses: actions/setup-dotnet@v2
  #       with:
  #         dotnet-version: 6.0.x
  #     - name: Restore
  #       run: dotnet restore "Mango.Web"
  #     - name: Build
  #       run: dotnet build "Mango.Web" --configuration Release --no-restore     
  #     - name: Bump versions
  #       uses: SiqiLu/dotnet-bump-version@2.0.0
  #       with:
  #           version_files: "**/*.csproj"
  #           version_mask: 0.0.1.0
  #           version_overwrite: "*.*.*.*"
  #           github_token: ${{ secrets.GITHUB_TOKEN }}
  dependabot:
    name: Dependabot fetch metadata
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-commit-verification: false
      # - name: Bump versions
      #   uses: SiqiLu/dotnet-bump-version@master
      #   with:
      #       version_files: "**/*.csproj"
      #       version_mask: 0.0.1
      #       version_overwrite: "*.*.*.*"
      #       github_token: ${{ secrets.GITHUB_TOKEN }}
  merge_to_develop:
    name: Merge to Develop by Dependabot
    runs-on: ubuntu-latest
    #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.actor == 'dependabot[bot]' }}    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch-name
        run: |
          echo "::set-output name=branch::$(echo $GITHUB_REF | sed 's/refs\/heads\///')"
        shell: bash

      - name: Validate and run action
        if: startsWith(steps.branch-name.outputs.branch, 'feature/')
        run: |
          # Add your workflow steps here
          - name: Bump versions
            uses: SiqiLu/dotnet-bump-version@2.0.0
            with:
              version_files: "**/*.csproj"
              version_mask: 0.0.1.0
              version_overwrite: "*.*.*.*"
              github_token: ${{ secrets.GITHUB_TOKEN }}

     
      
