---
name: BUMP Api version
on:
  push:
    branches:
      #- 'main'
      - 'feature/**'
      - 'dependabot/**'
    pusher:
      username: jalexispoveda
    
jobs:
  print_github_context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print github.context
        run: |
          echo "GitHub Context:"
          echo "GitHub Repository: $GITHUB_REPOSITORY"
          echo "GitHub Actor: $GITHUB_ACTOR"
  setup-user:
    needs: print_github_context
    name: Set github user2
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # - name: Creando el comit tinti
      #   uses: velocibear/create-empty-commit@v1.0.0
      #   with:
      #       token: ${{ secrets.GITHUB_TOKEN }}
      #       email: jalexispoveda1@gmail.com
      #       name: alekei
      #       message: Commit pa probar y sha
      
      - uses: actions/checkout@v3
      - run: git config --global user.email "jalexispoveda010@gmail.com"
      - run: git config --global user.name "jalexispoveda"
   #   - run: git commit --allow-empty -m "Update pusher"
   #   - run: git push
  upgrade_version:
    needs: setup-user
    name: Upgrade NET Version specific user
    runs-on: windows-latest
    # if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Bump versions
        uses: SiqiLu/dotnet-bump-version@2.0.0
        with:
          version_files: "**/*.csproj"
          version_mask: 0.0.1.0
          version_overwrite: "*.*.*.*"
          github_token: ${{ secrets.GITHUB_TOKEN }}

  
